In [1]:
import numpy as np
import pandas as pd
from faker import Faker

## Series

In [37]:
fake = Faker('fa')
np.array([1,2,3]) #1-D #Series

array([1, 2, 3])

np.random.randin(3,4)

In [38]:
np.random.rand(3,4) #2-D #DF

array([[0.29798116, 0.77501958, 0.27886057, 0.16273786],
       [0.26078511, 0.9625223 , 0.47709567, 0.09929648],
       [0.71249804, 0.04360891, 0.48009415, 0.24591876]])

In [39]:
pd.Series([1,2,3]) #(data, index)

0    1
1    2
2    3
dtype: int64

In [40]:
#pandas is on top numpy so lets create a series based on np
s = pd.Series(np.random.randn(5),
         index=['a','b', 'c', 'd', 'f'],
         dtype= 'float32')

In [41]:
s

a    0.907619
b    1.366508
c   -1.122649
d    1.328732
f    0.988318
dtype: float32

In [42]:
s.index

Index(['a', 'b', 'c', 'd', 'f'], dtype='object')

In [43]:
s[:2]

a    0.907619
b    1.366508
dtype: float32

In [44]:
s[s> s.median()]

b    1.366508
d    1.328732
dtype: float32

In [45]:
s.median()

0.988317608833313

In [46]:
s.dtype

dtype('float32')

In [47]:
s.to_numpy()

array([ 0.90761924,  1.3665082 , -1.1226492 ,  1.3287321 ,  0.9883176 ],
      dtype=float32)

## Vectorized operations and label alignments w/ series

In [48]:
s +s

a    1.815238
b    2.733016
c   -2.245298
d    2.657464
f    1.976635
dtype: float32

In [49]:
s * 2

a    1.815238
b    2.733016
c   -2.245298
d    2.657464
f    1.976635
dtype: float32

In [50]:
# create np array
a = np.random.randn(4)

In [51]:
a

array([ 1.14568489, -0.98938627,  0.73676358, -0.25662931])

In [52]:
a[:2]

array([ 1.14568489, -0.98938627])

In [53]:
a[2:]

array([ 0.73676358, -0.25662931])

In [54]:
a[:2] + a[2:]

array([ 1.88244847, -1.24601558])

In [55]:
s = pd.Series(np.random.rand(4), index= ['a','b', 'c', 'd'])

## Numpy VS Pandas allignment in operatins!!!

In [56]:
s

a    0.417153
b    0.353657
c    0.832541
d    0.406177
dtype: float64

In [57]:
s[:2]

a    0.417153
b    0.353657
dtype: float64

In [58]:
s[1:]

b    0.353657
c    0.832541
d    0.406177
dtype: float64

In [59]:
s[:2] +  s[1:]

a         NaN
b    0.707313
c         NaN
d         NaN
dtype: float64

## DataFrame

In [60]:
#you can make Dataframe from a series 
# MUST BE ITERABLE
d = {
    'age' : pd.Series(np.random.randint(0,80, 15)),
    'name' : pd.Series([fake.name() for i in range(20)])

}

In [61]:
df =pd.DataFrame(d)

In [62]:
pd.DataFrame(d, columns=['age'])

age
0    21
1    17
2    31
3    68
4    22
5    26
6     6
7    74
8    27
9    46
10   57
11   13
12   51
13   78
14   32

In [63]:
df = pd.DataFrame(d, columns=['age','esm'])

In [77]:
df

age                                name
0   67.0                  فاطمياسارينا جهانی
1   34.0                          یاسین رسته
2   58.0                       الینا ایروانی
3   39.0               جناب آقای سبحان زمانی
4   76.0                 فاطمه زهرا محمد پور
5   24.0                      پارسا ترکاشوند
6    9.0                         طاها روحانی
7   38.0                     امیرمهدی سماوات
8   34.0                     اميرمحمد سماوات
9   10.0                      علی اكبر طلوعی
10  65.0             سرکار خانم مهديس سلطانی
11  29.0              سرکار خانم مائده معروف
12  78.0                        زينب شادروان
13  44.0                         احسان رسولی
14  12.0                         رها نیلوفری
15   NaN                          باران ظفری
16   NaN                         سارا هوشیار
17   NaN                          کيان صارمی
18   NaN  سرکار خانم دکتر فاطمياسارينا زارعی
19   NaN              سرکار خانم نرگس سلطانی

In [78]:
df.columns =['sen', 'esm']

In [79]:
df

sen                                 esm
0   67.0                  فاطمياسارينا جهانی
1   34.0                          یاسین رسته
2   58.0                       الینا ایروانی
3   39.0               جناب آقای سبحان زمانی
4   76.0                 فاطمه زهرا محمد پور
5   24.0                      پارسا ترکاشوند
6    9.0                         طاها روحانی
7   38.0                     امیرمهدی سماوات
8   34.0                     اميرمحمد سماوات
9   10.0                      علی اكبر طلوعی
10  65.0             سرکار خانم مهديس سلطانی
11  29.0              سرکار خانم مائده معروف
12  78.0                        زينب شادروان
13  44.0                         احسان رسولی
14  12.0                         رها نیلوفری
15   NaN                          باران ظفری
16   NaN                         سارا هوشیار
17   NaN                          کيان صارمی
18   NaN  سرکار خانم دکتر فاطمياسارينا زارعی
19   NaN              سرکار خانم نرگس سلطانی

## pandas does view memory not copy!

In [25]:
a = np.arange(10)
b= pd.Series(a) #memory view by default

In [32]:
b= pd.Series(np.random.randint(10,29, 10), copy=True) #cop only works w ndarray , series!, other ds by default will get copied, same for DF

In [28]:
b

0    27
1    10
2    23
3    16
4    20
5    19
6    12
7    18
8    20
9    13
dtype: int64

In [29]:
b[0] = 10

In [30]:
b #memory view

0    10
1    10
2    23
3    16
4    20
5    19
6    12
7    18
8    20
9    13
dtype: int64

In [33]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## column selection, addition

In [64]:
df = pd.DataFrame(d)

In [65]:
df

age                         name
0   21.0                 دانيال شاکری
1   17.0               ابوالفضل هدایت
2   31.0                فاطمه حریریان
3   68.0                 آيناز چنگیزی
4   22.0                    رضا رفیعی
5   26.0                 پرهام کرمانی
6    6.0                 آیلین لاهوتی
7   74.0               امیرعباس ربانی
8   27.0                   رها مجتبوی
9   46.0                   سارا شبیری
10  57.0                 مبينا زنجانی
11  13.0           فاطمياسارينا ربانی
12  51.0                  کيانا سمسار
13  78.0                  ستایش عزیزی
14  32.0            فاطمه زهرا نوروزی
15   NaN                 احسان نوبختی
16   NaN             محمد مهدی کرمانی
17   NaN                  آریا هوشیار
18   NaN   سرکار خانم دکتر سارا صیادی
19   NaN  سرکار خانم دکتر هانيه کریمی

In [70]:
df['old'] = df['age'] > 50

In [71]:
df

age                         name    old
0   21.0                 دانيال شاکری  False
1   17.0               ابوالفضل هدایت  False
2   31.0                فاطمه حریریان  False
3   68.0                 آيناز چنگیزی   True
4   22.0                    رضا رفیعی  False
5   26.0                 پرهام کرمانی  False
6    6.0                 آیلین لاهوتی  False
7   74.0               امیرعباس ربانی   True
8   27.0                   رها مجتبوی  False
9   46.0                   سارا شبیری  False
10  57.0                 مبينا زنجانی   True
11  13.0           فاطمياسارينا ربانی  False
12  51.0                  کيانا سمسار   True
13  78.0                  ستایش عزیزی   True
14  32.0            فاطمه زهرا نوروزی  False
15   NaN                 احسان نوبختی  False
16   NaN             محمد مهدی کرمانی  False
17   NaN                  آریا هوشیار  False
18   NaN   سرکار خانم دکتر سارا صیادی  False
19   NaN  سرکار خانم دکتر هانيه کریمی  False

In [74]:
df['young'] = df['age'] < 20

In [75]:
df

age                         name    old  young
0   21.0                 دانيال شاکری  False  False
1   17.0               ابوالفضل هدایت  False   True
2   31.0                فاطمه حریریان  False  False
3   68.0                 آيناز چنگیزی   True  False
4   22.0                    رضا رفیعی  False  False
5   26.0                 پرهام کرمانی  False  False
6    6.0                 آیلین لاهوتی  False   True
7   74.0               امیرعباس ربانی   True  False
8   27.0                   رها مجتبوی  False  False
9   46.0                   سارا شبیری  False  False
10  57.0                 مبينا زنجانی   True  False
11  13.0           فاطمياسارينا ربانی  False   True
12  51.0                  کيانا سمسار   True  False
13  78.0                  ستایش عزیزی   True  False
14  32.0            فاطمه زهرا نوروزی  False  False
15   NaN                 احسان نوبختی  False  False
16   NaN             محمد مهدی کرمانی  False  False
17   NaN                  آریا هوشیار  False  False
18   NaN   سرکار خانم دکتر سارا صیادی  False  False
19   NaN  سرکار خانم دکتر هانيه کریمی  False  False

In [76]:
del df['young']

In [77]:
df

age                         name    old
0   21.0                 دانيال شاکری  False
1   17.0               ابوالفضل هدایت  False
2   31.0                فاطمه حریریان  False
3   68.0                 آيناز چنگیزی   True
4   22.0                    رضا رفیعی  False
5   26.0                 پرهام کرمانی  False
6    6.0                 آیلین لاهوتی  False
7   74.0               امیرعباس ربانی   True
8   27.0                   رها مجتبوی  False
9   46.0                   سارا شبیری  False
10  57.0                 مبينا زنجانی   True
11  13.0           فاطمياسارينا ربانی  False
12  51.0                  کيانا سمسار   True
13  78.0                  ستایش عزیزی   True
14  32.0            فاطمه زهرا نوروزی  False
15   NaN                 احسان نوبختی  False
16   NaN             محمد مهدی کرمانی  False
17   NaN                  آریا هوشیار  False
18   NaN   سرکار خانم دکتر سارا صیادی  False
19   NaN  سرکار خانم دکتر هانيه کریمی  False

In [78]:
#alignment n addition of the column
df['5 or older age'] = df['age'][:5]

In [79]:
df

age                         name    old  5 or older age
0   21.0                 دانيال شاکری  False            21.0
1   17.0               ابوالفضل هدایت  False            17.0
2   31.0                فاطمه حریریان  False            31.0
3   68.0                 آيناز چنگیزی   True            68.0
4   22.0                    رضا رفیعی  False            22.0
5   26.0                 پرهام کرمانی  False             NaN
6    6.0                 آیلین لاهوتی  False             NaN
7   74.0               امیرعباس ربانی   True             NaN
8   27.0                   رها مجتبوی  False             NaN
9   46.0                   سارا شبیری  False             NaN
10  57.0                 مبينا زنجانی   True             NaN
11  13.0           فاطمياسارينا ربانی  False             NaN
12  51.0                  کيانا سمسار   True             NaN
13  78.0                  ستایش عزیزی   True             NaN
14  32.0            فاطمه زهرا نوروزی  False             NaN
15   NaN                 احسان نوبختی  False             NaN
16   NaN             محمد مهدی کرمانی  False             NaN
17   NaN                  آریا هوشیار  False             NaN
18   NaN   سرکار خانم دکتر سارا صیادی  False             NaN
19   NaN  سرکار خانم دکتر هانيه کریمی  False             NaN

In [80]:
#add columnn in mid 
df.insert(1,'oldish', df['age']> 60)

In [81]:
df

age  oldish                         name    old  5 or older age
0   21.0   False                 دانيال شاکری  False            21.0
1   17.0   False               ابوالفضل هدایت  False            17.0
2   31.0   False                فاطمه حریریان  False            31.0
3   68.0    True                 آيناز چنگیزی   True            68.0
4   22.0   False                    رضا رفیعی  False            22.0
5   26.0   False                 پرهام کرمانی  False             NaN
6    6.0   False                 آیلین لاهوتی  False             NaN
7   74.0    True               امیرعباس ربانی   True             NaN
8   27.0   False                   رها مجتبوی  False             NaN
9   46.0   False                   سارا شبیری  False             NaN
10  57.0   False                 مبينا زنجانی   True             NaN
11  13.0   False           فاطمياسارينا ربانی  False             NaN
12  51.0   False                  کيانا سمسار   True             NaN
13  78.0    True                  ستایش عزیزی   True             NaN
14  32.0   False            فاطمه زهرا نوروزی  False             NaN
15   NaN   False                 احسان نوبختی  False             NaN
16   NaN   False             محمد مهدی کرمانی  False             NaN
17   NaN   False                  آریا هوشیار  False             NaN
18   NaN   False   سرکار خانم دکتر سارا صیادی  False             NaN
19   NaN   False  سرکار خانم دکتر هانيه کریمی  False             NaN

In [86]:
df

age  oldish                         name    old
0   21.0   False                 دانيال شاکری  False
1   17.0   False               ابوالفضل هدایت  False
2   31.0   False                فاطمه حریریان  False
3   68.0    True                 آيناز چنگیزی   True
4   22.0   False                    رضا رفیعی  False
5   26.0   False                 پرهام کرمانی  False
6    6.0   False                 آیلین لاهوتی  False
7   74.0    True               امیرعباس ربانی   True
8   27.0   False                   رها مجتبوی  False
9   46.0   False                   سارا شبیری  False
10  57.0   False                 مبينا زنجانی   True
11  13.0   False           فاطمياسارينا ربانی  False
12  51.0   False                  کيانا سمسار   True
13  78.0    True                  ستایش عزیزی   True
14  32.0   False            فاطمه زهرا نوروزی  False
15   NaN   False                 احسان نوبختی  False
16   NaN   False             محمد مهدی کرمانی  False
17   NaN   False                  آریا هوشیار  False
18   NaN   False   سرکار خانم دکتر سارا صیادی  False
19   NaN   False  سرکار خانم دکتر هانيه کریمی  False

# DataFrame II

In [2]:
import seaborn as sns

In [93]:
df = sns.load_dataset('iris')

In [95]:
df.to_csv('./iris.csv')

In [99]:
iris = pd.read_csv('./iris.csv')

In [100]:
iris

Unnamed: 0  sepal_length  sepal_width  petal_length  petal_width  \
0             0           5.1          3.5           1.4          0.2   
1             1           4.9          3.0           1.4          0.2   
2             2           4.7          3.2           1.3          0.2   
3             3           4.6          3.1           1.5          0.2   
4             4           5.0          3.6           1.4          0.2   
..          ...           ...          ...           ...          ...   
145         145           6.7          3.0           5.2          2.3   
146         146           6.3          2.5           5.0          1.9   
147         147           6.5          3.0           5.2          2.0   
148         148           6.2          3.4           5.4          2.3   
149         149           5.9          3.0           5.1          1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 6 columns]

In [102]:
iris.head(7)

Unnamed: 0  sepal_length  sepal_width  petal_length  petal_width species
0           0           5.1          3.5           1.4          0.2  setosa
1           1           4.9          3.0           1.4          0.2  setosa
2           2           4.7          3.2           1.3          0.2  setosa
3           3           4.6          3.1           1.5          0.2  setosa
4           4           5.0          3.6           1.4          0.2  setosa
5           5           5.4          3.9           1.7          0.4  setosa
6           6           4.6          3.4           1.4          0.3  setosa

In [103]:
iris.tail()

Unnamed: 0  sepal_length  sepal_width  petal_length  petal_width  \
145         145           6.7          3.0           5.2          2.3   
146         146           6.3          2.5           5.0          1.9   
147         147           6.5          3.0           5.2          2.0   
148         148           6.2          3.4           5.4          2.3   
149         149           5.9          3.0           5.1          1.8   

       species  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica

In [109]:
#add column
iris.assign(area= df['sepal_length']*df['sepal_width'] + df['petal_length']*df['petal_width'])

Unnamed: 0  sepal_length  sepal_width  petal_length  petal_width  \
0             0           5.1          3.5           1.4          0.2   
1             1           4.9          3.0           1.4          0.2   
2             2           4.7          3.2           1.3          0.2   
3             3           4.6          3.1           1.5          0.2   
4             4           5.0          3.6           1.4          0.2   
..          ...           ...          ...           ...          ...   
145         145           6.7          3.0           5.2          2.3   
146         146           6.3          2.5           5.0          1.9   
147         147           6.5          3.0           5.2          2.0   
148         148           6.2          3.4           5.4          2.3   
149         149           5.9          3.0           5.1          1.8   

       species   area  
0       setosa  18.13  
1       setosa  14.98  
2       setosa  15.30  
3       setosa  14.56  
4       setosa  18.28  
..         ...    ...  
145  virginica  32.06  
146  virginica  25.25  
147  virginica  29.90  
148  virginica  33.50  
149  virginica  26.88  

[150 rows x 7 columns]

In [110]:
del iris['Unnamed: 0']

In [111]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [125]:
#estekhraj data #alternati
df_new =iris.query('petal_length > 5').assign(
    PetalRatio = lambda x: x['petal_length'] / x['petal_width'],
    SepalRatio = lambda x: x['sepal_length'] / x['sepal_width'],
    upper_case = lambda x: x['species'].str.upper()
) #Lambda can be any function

In [126]:
df_new

sepal_length  sepal_width  petal_length  petal_width     species  \
83            6.0          2.7           5.1          1.6  versicolor   
100           6.3          3.3           6.0          2.5   virginica   
101           5.8          2.7           5.1          1.9   virginica   
102           7.1          3.0           5.9          2.1   virginica   
103           6.3          2.9           5.6          1.8   virginica   
104           6.5          3.0           5.8          2.2   virginica   
105           7.6          3.0           6.6          2.1   virginica   
107           7.3          2.9           6.3          1.8   virginica   
108           6.7          2.5           5.8          1.8   virginica   
109           7.2          3.6           6.1          2.5   virginica   
110           6.5          3.2           5.1          2.0   virginica   
111           6.4          2.7           5.3          1.9   virginica   
112           6.8          3.0           5.5          2.1   virginica   
114           5.8          2.8           5.1          2.4   virginica   
115           6.4          3.2           5.3          2.3   virginica   
116           6.5          3.0           5.5          1.8   virginica   
117           7.7          3.8           6.7          2.2   virginica   
118           7.7          2.6           6.9          2.3   virginica   
120           6.9          3.2           5.7          2.3   virginica   
122           7.7          2.8           6.7          2.0   virginica   
124           6.7          3.3           5.7          2.1   virginica   
125           7.2          3.2           6.0          1.8   virginica   
128           6.4          2.8           5.6          2.1   virginica   
129           7.2          3.0           5.8          1.6   virginica   
130           7.4          2.8           6.1          1.9   virginica   
131           7.9          3.8           6.4          2.0   virginica   
132           6.4          2.8           5.6          2.2   virginica   
133           6.3          2.8           5.1          1.5   virginica   
134           6.1          2.6           5.6          1.4   virginica   
135           7.7          3.0           6.1          2.3   virginica   
136           6.3          3.4           5.6          2.4   virginica   
137           6.4          3.1           5.5          1.8   virginica   
139           6.9          3.1           5.4          2.1   virginica   
140           6.7          3.1           5.6          2.4   virginica   
141           6.9          3.1           5.1          2.3   virginica   
142           5.8          2.7           5.1          1.9   virginica   
143           6.8          3.2           5.9          2.3   virginica   
144           6.7          3.3           5.7          2.5   virginica   
145           6.7          3.0           5.2          2.3   virginica   
147           6.5          3.0           5.2          2.0   virginica   
148           6.2          3.4           5.4          2.3   virginica   
149           5.9          3.0           5.1          1.8   virginica   

     PetalRatio  SepalRatio  upper_case  
83     3.187500    2.222222  VERSICOLOR  
100    2.400000    1.909091   VIRGINICA  
101    2.684211    2.148148   VIRGINICA  
102    2.809524    2.366667   VIRGINICA  
103    3.111111    2.172414   VIRGINICA  
104    2.636364    2.166667   VIRGINICA  
105    3.142857    2.533333   VIRGINICA  
107    3.500000    2.517241   VIRGINICA  
108    3.222222    2.680000   VIRGINICA  
109    2.440000    2.000000   VIRGINICA  
110    2.550000    2.031250   VIRGINICA  
111    2.789474    2.370370   VIRGINICA  
112    2.619048    2.266667   VIRGINICA  
114    2.125000    2.071429   VIRGINICA  
115    2.304348    2.000000   VIRGINICA  
116    3.055556    2.166667   VIRGINICA  
117    3.045455    2.026316   VIRGINICA  
118    3.000000    2.961538   VIRGINICA  
120    2.478261    2.156250   VIRGINICA  
122    3.350000    2.7500

## Selection n Indexing of rows!

In [131]:
df = pd.DataFrame(np.random.rand(3, 4), index=['a','b', 'c'])

In [132]:
df

0         1         2         3
a  0.478707  0.786089  0.795368  0.874898
b  0.311872  0.590416  0.828893  0.594592
c  0.008791  0.845461  0.803188  0.107410

In [135]:
#get first row
df.loc['a'] #get the index

0    0.478707
1    0.786089
2    0.795368
3    0.874898
Name: a, dtype: float64

In [136]:
df.iloc[0] #get the index

0    0.478707
1    0.786089
2    0.795368
3    0.874898
Name: a, dtype: float64

## Alignment 

In [137]:
df1 = pd.DataFrame(np.random.rand(3,4), index=['a','b', 'c'])

In [138]:
df2 = pd.DataFrame(np.random.rand(4,5), index=['a','b', 'c', 'd'])

In [139]:
df1

0         1         2         3
a  0.943356  0.826815  0.614120  0.903692
b  0.734754  0.266477  0.813400  0.637968
c  0.913642  0.721594  0.399574  0.245133

In [140]:
df2

0         1         2         3         4
a  0.075757  0.498800  0.931260  0.223753  0.825800
b  0.946583  0.810573  0.850619  0.689904  0.773484
c  0.256852  0.898308  0.299638  0.476520  0.747702
d  0.792813  0.682790  0.632233  0.841555  0.772989

In [141]:
df1 + df2

0         1         2         3   4
a  1.019114  1.325615  1.545381  1.127445 NaN
b  1.681337  1.077050  1.664018  1.327871 NaN
c  1.170494  1.619902  0.699212  0.721654 NaN
d       NaN       NaN       NaN       NaN NaN

In [142]:
#transposs, row snd column will be exchanges
df1.T

a         b         c
0  0.943356  0.734754  0.913642
1  0.826815  0.266477  0.721594
2  0.614120  0.813400  0.399574
3  0.903692  0.637968  0.245133

## console display

In [3]:
df = sns.load_dataset('titanic')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [5]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [6]:
df.insert(0, 'Upper', df['embark_town'].str.upper())

In [7]:
df

Upper  survived  pclass     sex   age  sibsp  parch     fare  \
0    SOUTHAMPTON         0       3    male  22.0      1      0   7.2500   
1      CHERBOURG         1       1  female  38.0      1      0  71.2833   
2    SOUTHAMPTON         1       3  female  26.0      0      0   7.9250   
3    SOUTHAMPTON         1       1  female  35.0      1      0  53.1000   
4    SOUTHAMPTON         0       3    male  35.0      0      0   8.0500   
..           ...       ...     ...     ...   ...    ...    ...      ...   
886  SOUTHAMPTON         0       2    male  27.0      0      0  13.0000   
887  SOUTHAMPTON         1       1  female  19.0      0      0  30.0000   
888  SOUTHAMPTON         0       3  female   NaN      1      2  23.4500   
889    CHERBOURG         1       1    male  26.0      0      0  30.0000   
890   QUEENSTOWN         0       3    male  32.0      0      0   7.7500   

    embarked   class    who  adult_male deck  embark_town alive  alone  
0          S   Third    man        True  NaN  Southampton    no  False  
1          C   First  woman       False    C    Cherbourg   yes  False  
2          S   Third  woman       False  NaN  Southampton   yes   True  
3          S   First  woman       False    C  Southampton   yes  False  
4          S   Third    man        True  NaN  Southampton    no   True  
..       ...     ...    ...         ...  ...          ...   ...    ...  
886        S  Second    man        True  NaN  Southampton    no   True  
887        S   First  woman       False    B  Southampton   yes   True  
888        S   Third  woman       False  NaN  Southampton    no  False  
889        C   First    man        True    C    Cherbourg   yes   True  
890        Q   Third    man        True  NaN   Queenstown    no   True  

[891 rows x 16 columns]

In [164]:
pd.options.display.max_colwidth = 6

In [162]:
#pd.options.display.max_columns = 6

In [163]:
df

Upper   path  survived  ...  embark_town alive  alone
0    SO...  SO...      0     ...  So...          no  False
1    CH...  CH...      1     ...  Ch...         yes  False
2    SO...  SO...      1     ...  So...         yes   True
3    SO...  SO...      1     ...  So...         yes  False
4    SO...  SO...      0     ...  So...          no   True
..     ...    ...    ...     ...    ...         ...    ...
886  SO...  SO...      0     ...  So...          no   True
887  SO...  SO...      1     ...  So...         yes   True
888  SO...  SO...      0     ...  So...          no  False
889  CH...  CH...      1     ...  Ch...         yes   True
890  QU...  QU...      0     ...  Qu...          no   True

[891 rows x 17 columns]

In [8]:
# raqam aashar
pd.options.display.precision = 3

In [9]:
df

Upper  survived  pclass     sex   age  sibsp  parch    fare  \
0    SOUTHAMPTON         0       3    male  22.0      1      0   7.250   
1      CHERBOURG         1       1  female  38.0      1      0  71.283   
2    SOUTHAMPTON         1       3  female  26.0      0      0   7.925   
3    SOUTHAMPTON         1       1  female  35.0      1      0  53.100   
4    SOUTHAMPTON         0       3    male  35.0      0      0   8.050   
..           ...       ...     ...     ...   ...    ...    ...     ...   
886  SOUTHAMPTON         0       2    male  27.0      0      0  13.000   
887  SOUTHAMPTON         1       1  female  19.0      0      0  30.000   
888  SOUTHAMPTON         0       3  female   NaN      1      2  23.450   
889    CHERBOURG         1       1    male  26.0      0      0  30.000   
890   QUEENSTOWN         0       3    male  32.0      0      0   7.750   

    embarked   class    who  adult_male deck  embark_town alive  alone  
0          S   Third    man        True  NaN  Southampton    no  False  
1          C   First  woman       False    C    Cherbourg   yes  False  
2          S   Third  woman       False  NaN  Southampton   yes   True  
3          S   First  woman       False    C  Southampton   yes  False  
4          S   Third    man        True  NaN  Southampton    no   True  
..       ...     ...    ...         ...  ...          ...   ...    ...  
886        S  Second    man        True  NaN  Southampton    no   True  
887        S   First  woman       False    B  Southampton   yes   True  
888        S   Third  woman       False  NaN  Southampton    no  False  
889        C   First    man        True    C    Cherbourg   yes   True  
890        Q   Third    man        True  NaN   Queenstown    no   True  

[891 rows x 16 columns]