In [1]:
import numpy as np
import pandas as pd

## Series

In [2]:
np.array([1,2,3]) #1-D #Series

array([1, 2, 3])

np.random.randin(3,4)

In [5]:
np.random.rand(3,4) #2-D #DF

array([[0.78319312, 0.17078852, 0.96172522, 0.24429456],
       [0.71406226, 0.69546958, 0.86381972, 0.96702235],
       [0.67609904, 0.95362343, 0.31161483, 0.0971299 ]])

In [6]:
pd.Series([1,2,3]) #(data, index)

0    1
1    2
2    3
dtype: int64

In [12]:
#pandas is on top numpy so lets create a series based on np
s = pd.Series(np.random.randn(5),
         index=['a','b', 'c', 'd', 'f'],
         dtype= 'float32')

In [13]:
s

a    0.159966
b    1.181451
c    0.763776
d    0.560322
f    1.637558
dtype: float32

In [14]:
s.index

Index(['a', 'b', 'c', 'd', 'f'], dtype='object')

In [15]:
s[:2]

a    0.159966
b    1.181451
dtype: float32

In [16]:
s[s> s.median()]

b    1.181451
f    1.637558
dtype: float32

In [17]:
s.median()

0.7637763023376465

In [19]:
s.dtype

dtype('float32')

In [20]:
s.to_numpy()

array([0.15996622, 1.1814506 , 0.7637763 , 0.56032175, 1.6375582 ],
      dtype=float32)

## Vectorized operations and label alignments w/ series

In [21]:
s +s

a    0.319932
b    2.362901
c    1.527553
d    1.120643
f    3.275116
dtype: float32

In [22]:
s * 2

a    0.319932
b    2.362901
c    1.527553
d    1.120643
f    3.275116
dtype: float32

In [23]:
# create np array
a = np.random.randn(4)

In [24]:
a

array([ 0.23864953, -0.56868532, -1.10492167, -1.20565626])

In [27]:
a[:2]

array([ 0.23864953, -0.56868532])

In [30]:
a[2:]

array([-1.10492167, -1.20565626])

In [31]:
a[:2] + a[2:]

array([-0.86627213, -1.77434158])

In [40]:
s = pd.Series(np.random.rand(4), index= ['a','b', 'c', 'd'])

## Numpy VS Pandas allignment in operatins!!!

In [41]:
s

a    0.322753
b    0.659787
c    0.500585
d    0.498348
dtype: float64

In [42]:
s[:2]

a    0.322753
b    0.659787
dtype: float64

In [43]:
s[1:]

b    0.659787
c    0.500585
d    0.498348
dtype: float64

In [44]:
s[:2] +  s[1:]

a         NaN
b    1.319573
c         NaN
d         NaN
dtype: float64