In [42]:
import numpy as np
import pandas as pd
from faker import Faker
fake = Faker('fa')

## Series

In [39]:
np.array([1,2,3]) #1-D #Series


array([1, 2, 3])

np.random.randin(3,4)

In [6]:
np.random.rand(3,4) #2-D #DF

array([[0.67167589, 0.89006385, 0.54723017, 0.26073994],
       [0.23344704, 0.9436706 , 0.14944798, 0.78893052],
       [0.0763484 , 0.0448026 , 0.68563547, 0.12872417]])

In [7]:
pd.Series([1,2,3]) #(data, index)

0    1
1    2
2    3
dtype: int64

In [8]:
#pandas is on top numpy so lets create a series based on np
s = pd.Series(np.random.randn(5),
         index=['a','b', 'c', 'd', 'f'],
         dtype= 'float32')

In [9]:
s

a    0.953700
b    1.299025
c   -0.083773
d    2.025198
f   -0.126045
dtype: float32

In [10]:
s.index

Index(['a', 'b', 'c', 'd', 'f'], dtype='object')

In [11]:
s[:2]

a    0.953700
b    1.299025
dtype: float32

In [12]:
s[s> s.median()]

b    1.299025
d    2.025198
dtype: float32

In [13]:
s.median()

0.9536998

In [14]:
s.dtype

dtype('float32')

In [15]:
s.to_numpy()

array([ 0.9536998 ,  1.2990249 , -0.08377292,  2.0251985 , -0.12604517],
      dtype=float32)

## Vectorized operations and label alignments w/ series

In [16]:
s +s

a    1.907400
b    2.598050
c   -0.167546
d    4.050397
f   -0.252090
dtype: float32

In [17]:
s * 2

a    1.907400
b    2.598050
c   -0.167546
d    4.050397
f   -0.252090
dtype: float32

In [18]:
# create np array
a = np.random.randn(4)

In [19]:
a

array([0.30191376, 0.75591083, 0.44820358, 0.16470612])

In [20]:
a[:2]

array([0.30191376, 0.75591083])

In [21]:
a[2:]

array([0.44820358, 0.16470612])

In [22]:
a[:2] + a[2:]

array([0.75011734, 0.92061695])

In [23]:
s = pd.Series(np.random.rand(4), index= ['a','b', 'c', 'd'])

## Numpy VS Pandas allignment in operatins!!!

In [24]:
s

a    0.189773
b    0.677121
c    0.989703
d    0.609521
dtype: float64

In [25]:
s[:2]

a    0.189773
b    0.677121
dtype: float64

In [26]:
s[1:]

b    0.677121
c    0.989703
d    0.609521
dtype: float64

In [27]:
s[:2] +  s[1:]

a         NaN
b    1.354242
c         NaN
d         NaN
dtype: float64

## DataFrame

In [46]:
#you can make Dataframe from a series 
d = {
    'age' : pd.Series(np.random.randint(0,80, 15)),
    'name' : pd.Series([fake.name() for i in range(20)])

}

In [47]:
pd.DataFrame(d)

age                          name
0   57.0                   آرش علیجانی
1   23.0              یگانه عبدالمالکی
2   27.0                    ثنا سماوات
3   47.0                    آيلين قاضی
4   32.0                 بنيامين طلوعی
5   55.0                   الینا هاشمی
6   21.0                   معصومه نوری
7   51.0                   نیایش سغیری
8    1.0  سرکار خانم دکتر پریا حریریان
9   66.0                    باران جنتی
10  51.0                 علیرضا منصوری
11  76.0                 دانيال کرمانی
12  29.0                   پارسا اشرفی
13  30.0                      آوا وثاق
14  37.0    سرکار خانم دکتر مریم موسوی
15   NaN                  معصومه رسولی
16   NaN                    حسام نعمتی
17   NaN            محمدياسين عبدالعلی
18   NaN                  یاسمین سعیدی
19   NaN                   آيلين دادفر

In [48]:
pd.DataFrame(d, columns=['age'])

age
0    57
1    23
2    27
3    47
4    32
5    55
6    21
7    51
8     1
9    66
10   51
11   76
12   29
13   30
14   37

In [50]:
df = pd.DataFrame(d)

In [51]:
df

age                          name
0   57.0                   آرش علیجانی
1   23.0              یگانه عبدالمالکی
2   27.0                    ثنا سماوات
3   47.0                    آيلين قاضی
4   32.0                 بنيامين طلوعی
5   55.0                   الینا هاشمی
6   21.0                   معصومه نوری
7   51.0                   نیایش سغیری
8    1.0  سرکار خانم دکتر پریا حریریان
9   66.0                    باران جنتی
10  51.0                 علیرضا منصوری
11  76.0                 دانيال کرمانی
12  29.0                   پارسا اشرفی
13  30.0                      آوا وثاق
14  37.0    سرکار خانم دکتر مریم موسوی
15   NaN                  معصومه رسولی
16   NaN                    حسام نعمتی
17   NaN            محمدياسين عبدالعلی
18   NaN                  یاسمین سعیدی
19   NaN                   آيلين دادفر

In [54]:
df.columns

Index(['age', 'name'], dtype='object')